### ISSUE TITLE
Cannot build simple turn-server example

### ISSUE THREAD

**Issue by s-sokolko** [pion/turn#135]
### Your environment.
  - Version: master
  - OS: Ubuntu Linux 16.04 LTS
  - go version go1.6.2 linux/amd64
  - my ENV vars:
`
export GOPATH=~/go
export GOBIN=$GOPATH/bin
`

### What did you do?
I pulled pion/turn project source code and checked it out to the master branch.
Then I cd to examples/turn-server/simple and tried to go build.

### What did you expect?
I expected to get the simple example built, but an error has occurred.

### What happened?
`$ go build
main.go:13:2: cannot find package "github.com/pion/turn/v2" in any of:
	/usr/lib/go-1.6/src/github.com/pion/turn/v2 (from $GOROOT)
	/home/user/go/src/github.com/pion/turn/v2 (from $GOPATH)`

I am quite new to go, so maybe I am doing something wrong? Any help appreciated!

**Comment by Sean-Der** [comment]
Hey @s-sokolko 

`pion/turn` requires Go 1.12 or greater, it uses Modules (that is where the `/v2` comes from in the URL)

**Comment by s-sokolko** [comment]
Thanks for the reply, @Sean-Der ! I will try updating go version and build the example again.
Sorry for the lame question: I like your project, but don't have experience with Go

**Comment by s-sokolko** [comment]
It worked like a charm, thanks!

**Comment by OmarHassanT** [comment]
> It worked like a charm, thanks!

I use 1.14.4 version but I faced the same problem. Can you please tell me how you run the file.
