### ISSUE TITLE
Stun server

### ISSUE THREAD

**Issue by jason-shen** [pion/turn#152]
Hi All 

First of all thisbproject is awesome, I have been looking through the sample code, didn't find a way to build a stun server, there are examples for a turn, can any.one point me to the right direction of build an stun from this

Thank you advance.

Jason

**Comment by Sean-Der** [comment]
Hey @jason-shen sorry for the delay on this.

This is a STUN server also! The logic for the server side is [here](https://github.com/pion/turn/blob/master/internal/server/stun.go) 

If you are interested it would be a great contribution to update the README to mention this :)
