### ISSUE TITLE
Different windows releases?

### ISSUE THREAD

**Issue by Varooneh** [pion/turn#171]
Hi,
I download pion turn windows release and extract it but I've 4 executable files:

1. `turn-server-add-software-attribute`
2. `turn-server-log`
3. `turn-server-simple`
4. `turn-server-tcp`

Which different between this files? which different between `turn-server-simple` & `turn-server-tcp`?

Also, can for turn user management can I connect to MSSQL database? and pion turn server can support stun or just turn support?

Thank you for help me.

**Comment by gmbad** [comment]
Hello Varooneh.

I also didn't find the difference between these binaries in the documentation.

I tested the turn-server-simple.exe option, but the webcam freezes after a few seconds.

The way was to go back to using version 1.4.0. (compiled by Go)

**Comment by jackyshaw2017** [comment]
if your app run on google chrome ，suggest simple ，tcp may work on  some  c/s software

**Comment by stv0g** [comment]
This package currently only ships with a few simple examples of TURN servers.
Its not really (yet) intended to be used as a production ready TURN server.

Please have a look at other solutions for that.
