### ISSUE TITLE
WebCam freezes after a few seconds

### ISSUE THREAD

**Issue by gmbad** [pion/turn#176]
Hi All!

I use version 1.4.0. Its works fine.

I tried to migrate to version 2.0.2, with the binary "turn-server-simple". But after a few seconds the webcam freezes.

Does anyone know what may be happening?

Thank you,

Gabriel

**Comment by Sean-Der** [comment]
That's not good! Do you see any logs like https://github.com/pion/turn/issues/146 ?

I haven't had a chance to look into this, but it sounds like we regressed. Would you mind doing a bisect, I would love to fix this.

What are the two clients you are running. What is the network you are in (can you reproduce this in your LAN) etc... if you can get this reproducible in a small way (or track down a commit) that would be super helpful.

thanks :)

**Comment by gmbad** [comment]
Hi Sean!

Thanks for helping.

My server is Windows 2020.

I am using version v2.0.2 of Pion.

I tested it on my own network with the Chrome browser. Version 86.0.4240.111

How can I generate this LOG, like  #146 ?

Thank you very much,

Gabriel

**Comment by gmbad** [comment]
Hello @Sean-Der 

Yes, them problem is the same like #146 

After 40 seconds, the connection fail.

Thanks,

Gabriel

**Comment by Sean-Der** [comment]
Closing as dump of #146 (going to start working on it now!)
