### ISSUE TITLE
Are credentials needed?

### ISSUE THREAD

**Issue by StanisalvPopadynets** [pion/turn#178]
It appears there is no ability to add ICE candidates with username and password where I want to use TURN server unlike some testing pages like https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/. My question is whether or not it is possible to run TURN server without users.

**Comment by Sean-Der** [comment]
@StanisalvPopadynets You set these details in the `AuthHandler` you can see an example [here](https://github.com/pion/turn/blob/master/examples/turn-server/simple/main.go#L50-L53)

We don't just take a list of credentials. This way you can integrate with other libraries/services (where all users aren't know up front, and you can delete them)

**Comment by Sean-Der** [comment]
Hey @StanisalvPopadynets

If you are still having issues please re-open! Thanks for using Pion
