### ISSUE TITLE
Add support for customizing SOFTWARE attribute value

### ISSUE THREAD

**Issue by kc5nra** [pion/turn#18]
Currently this is hard-coded and should be specifiable either through configuration or environment variables.

**Comment by Sean-Der** [comment]
This is a great issue for a first time contributor! 

You just need to modify `StartArguments` to include an optional value. This can then be passed via `NewSoftware` 

This could be great for debugging/analysis if people are using multiple TURN servers.

**Comment by namreg** [comment]
@Sean-Der I have filed the PR. Check it out, please, when you will have a time
