### ISSUE TITLE
Distributed solution？

### ISSUE THREAD

**Issue by iammeizu** [pion/turn#198]
## Summary

Need distributed turn solution to achieve high performance and high availability.

## Describe alternatives you've considered

coturn solution: https://github.com/coturn/coturn/wiki/TURN-Performance-and-Load-Balance

**Comment by putrafajarh** [comment]
im thinking use Dockerized and use AWS Network Load Balancer,

**Comment by jech** [comment]
I'm not sure what this issue is requesting.

There's nothing preventing you from deploying an army of TURN servers, and using a frontend that returns alternate server replies.  A cleaner solution would be to have the clients load distribute, by having a different ICEConfiguration for each client.

**Comment by iammeizu** [comment]
I try to deploying a cluster of turn servers behind a load balancer, but it's not work, because turn seems to use different ports to provide relay candidate and transfer data. Maybe I need a service finder to monitor turn servers and provide high performance.

**Comment by rg0now** [comment]
STUNner solves this exact problem with Kubernetes:  https://github.com/l7mp/stunner

**Comment by stv0g** [comment]
Load-balancing using a 5-tuple should work as each client gets assigned to the same TURN server as long its tuple stays the same. So there is no need to synchronize allocations/permissions between the servers.

I dont think synchronizing state between a fleet of distributed TURN servers is necessary here.

I will close the issue unless the issue creator further details what feature he is missing.
