### ISSUE TITLE
Bind to port 80 or 443 permission denied?

### ISSUE THREAD

**Issue by putrafajarh** [pion/turn#202]
Hi i got error when try to bind to port 80 tcp / udp

./tcp -users putra=fajar -public-ip 127.0.0.1 -port 80

panic: Failed to create TURN server listener: listen tcp4 0.0.0.0:80: bind: permission denied

**Comment by at-wat** [comment]
Hi @putrafajarh, TCP/IP ports below 1024 are specified as privileged ports and *nix systems like Linux don't allow normal users to listen to these ports. Running the command with `sudo` to run as root is the simplest way to make it work. 

If you are using Linux, adding `CAP_NET_BIND_SERVICE` capability to the program by `setcap` command also allows the program to use privileged ports.

refs:
- https://man7.org/linux/man-pages/man7/capabilities.7.html
- https://man7.org/linux/man-pages/man8/setcap.8.html
