### ISSUE TITLE
Create a simple turn server with API that allows you to create temporary credentials

### ISSUE THREAD

**Issue by kc5nra** [pion/turn#21]
This can store the temporary users in the go process or use a cache like redis.  This would prevent abuse of the TURN bandwidth if user/pass leak

**Comment by iwittkau** [comment]
There is a draft related to this: [A REST API For Access To TURN Services](https://tools.ietf.org/html/draft-uberti-behave-turn-rest-00).

**Comment by Sean-Der** [comment]
Nice!

Yea I was thinking of starting an `examples` directory and implementing this (and some other examples) I think that is our best bet.

That way when people `go get` they get the really simple client/server, then if they want they can build the examples if they want. We can also do other cool ones I was thinking.

* Example redis integration
* Example REST API
* Example MySQL

**Comment by Sean-Der** [comment]
Since this issue is so ambiguous/no clear way to close I am going to resolve for now.

I would love to have more examples though! I just don't plan on acting on this, and don't have plans for the near future.

**Comment by kilroy05** [comment]
As a new (potential) user of turn, would also love to see some examples with redis / rest / mysql
(I know it's an old topic, issue still there for me :) )
