### ISSUE TITLE
TURN without SSL

### ISSUE THREAD

**Issue by alexrierra** [pion/turn#210]
May be a stupid question. But, is it safe to use TURN server without SSL encryption and certificate?  I know WebRTC encrypts its traffic with Secure Realtime Protocol.
What are the dangers of such use? Interception of traffic?

**Comment by Sean-Der** [comment]
Hey @alexrierra 

Many people do run TURN over UDP/TCP only (without TLS). I don't think it poses anymore risk then running your traffic over the internet in general.

For the security of client -> TURN server TLS is nice! It prevents anyone from monitoring or modifying the traffic. You can also be certain that the TURN server you are connecting too is who it claims.

Happy to talk about this more in [Slack](https://pion.ly/slack) but don't have any specific feedback about it.
