### ISSUE TITLE
Tags and releases don't match (latest release v2.0.2, latest tag v2.0.5)

### ISSUE THREAD

**Issue by jawnsy** [pion/turn#227]
The last few releases have tags created, but no corresponding GitHub Release. This looks a bit unusual in the GitHub user interface (bottom right of the [main repository screen](https://github.com/pion/turn/)), since users see that the latest release is v2.0.2, published Jan 29 2020:

![image](https://user-images.githubusercontent.com/52710/128644314-46b77620-fe3b-4b00-a32e-748272d23fc9.png)

Yet, anyone adding pion as a dependency to their go.mod will see v2.0.5, since that's the latest tag:

```
require (
        github.com/pion/turn/v2 v2.0.5
)
```

This looks a little confusing. Would you consider creating the missing releases?

The [Releases page](https://github.com/pion/turn/releases) does helpfully show that there are newer tags, and also provides compiled release build archives (whereas the tags do not):

![image](https://user-images.githubusercontent.com/52710/128644398-eba1223a-4ed2-47a6-bcf9-bbd5d9654f57.png)

**Comment by stv0g** [comment]
@jawnsy Thats pretty normal for the Pion related packages.

The CI is not creating releases automatically. I assume those have been created by hand in the past and now are simply forgotten.
