### ISSUE TITLE
example/turn_client/udp failed to get attribute NONES

### ISSUE THREAD

**Issue by tubzby** [pion/turn#228]
Not sure if this a coturn issue or not.

### Your environment.
  - Version: 72ffd594f7c6104b5680a4fea5651928e3b6ddb4
  - Browser: Not related
  - Other Information -  Using coturn with docker image: coturn/coturn.

### What did you do?
```bash
go run main.go -host {COTURN SERVER} -ping -port 3478 -user USER=PASSWORD

panic: attribute not found

goroutine 1 [running]:
main.main()
	/Users/AAAA/src/turn/examples/turn-client/udp/main.go:73 +0x674
exit status 2
```

### What did you expect?
turn_client example runs.

### What happened?
turn_client example failed to run with panic

**Comment by tubzby** [comment]
It seems that my server is not enabling authentication, succeed after authentication is enabled.

but it's still a compatible problem in my opinion.

**Comment by Sean-Der** [comment]
Nice catch!

I think a better error message here would be fantastic. I am unsure if it is a good idea to support no authentication. I don't want to suggest anything to users that could cause harm.

TURN has some great features like Long-Term Credential Mechanism with a seed that make it really easy.
