### ISSUE TITLE
Dockerfile and docker-compose files for the examples.

### ISSUE THREAD

**Issue by shreehari-a** [pion/turn#238]
## Summary

I tried the turn server example for one of the webrtc projects. It came to my observation, there's no docker-compose file for the examples to try out really quickly, so I would like people to have a docker-compose file for using the turn server quickly. I have made a Dockerfile and docker-compose file, please let me know if I can create a PR with the same. 

## Motivation

+ Why are we doing this?
  + quick trial through docker-compose
  + a base Dockerfile, dock-compose file which can be extended according to user's needs.
  + easy to incorporate with any dockerized environment.
+ What use cases does it support? 
  + installation of turn server in any dockerized environment.
+ What is the expected outcome? 
  + Additional docker file and docker-compose files in examples
+ Is this available in other implementations? 
  + I was not able to find a well-maintained version of the docker-compose file.

**Comment by stv0g** [comment]
I will close this in favor of #151
