### ISSUE TITLE
The same credentials for multiple connections

### ISSUE THREAD

**Issue by serdor2** [pion/turn#240]
Thanks for great project! I am using your simple turn for Window.  
May be a stupid question...  Is it possible to use the same username and password  in TURN for multiple connections?  Or I need to set separate username=password pair for each connection?

For example, I have   3 pairs of PCs.   Can I use the same username=password in simple PION TURN for all these simultaneous connections ? Thanks!

**Comment by Sean-Der** [comment]
Hey @serdor2 

Yes you can use the same username/password! It is checked when connecting. If you want to enforce limits/lifetimes on them you would have to implement that part.

thanks for using Pion :)
