### ISSUE TITLE
Is it possible to set turn-server public-ip to a DNS name accessible by the client?

### ISSUE THREAD

**Issue by naive924** [pion/turn#244]
Could you please advise me.

## Summary
There is the following description. https://github.com/pion/turn/tree/master/examples
> -public-ip : IP that your TURN server is reachable on, for local development then can just be your local IP, avoid using 127.0.0.1 as some browsers discard from that IP.

Is it possible to set the public-ip of turn-server to a DNS name accessible by the client? Specifically, it is as follows.
`$turn-server-log -public-ip ${DNSName} -port 3478 -users username=password,foo=bar`

## Motivation
Because the IP address may change and we want to access with DNS Name.

**Comment by Sean-Der** [comment]
Hey @naive924 

This is possible today! I would copy the `RelayAddressGeneratorStatic` and replace `RelayAddress` so instead uses w/e service you want to lookup the IP with.

TURN itself requires that an IP is sent in the Allocate response. You will need to handle the dynamic determination of the IP yourself unfortunately. 

If you need more help happy to answer here or on [Slack](https://pion.ly/slack)

**Comment by naive924** [comment]
Hi @Sean-Der 
Thank you for your reply.

I tried this with v2.0.2.
`$turn-server-log -public-ip ${DNSName} -port 3478 -users username=password,foo=bar`

I got the following error. 
Is it possible to specify only the IP address for `public-ip`? (DNS name cannot be specified).
```
2022/02/22 14:33:52 turn: RelayAddress must be valid IP to use RelayAddressGeneratorStatic
panic: turn: RelayAddress must be valid IP to use RelayAddressGeneratorStatic

goroutine 1 [running]:
log.Panic(0xc000087ec0, 0x1, 0x1)
        /opt/go/src/log/log.go:338 +0xb3
main.main()
        /home/sean/go/src/github.com/pion/turn/examples/turn-server/log/main.go:101 +0x72b
```

**Comment by Zoidberg2** [comment]
I have the same problem as the guy above. but i dont have Slack. are you guys reachable from XMPP? 
or if you can maybe point us to the right direction.
