### ISSUE TITLE
Too many open files bug

### ISSUE THREAD

**Issue by superp00t** [pion/turn#27]
After running the server for a day and getting a regular influx of users, I was unable to use the TURN server and got many of these errors in the console: 

```
2018/12/07 17:32:57 Failed to handle ALLOCATE-REQUEST from x.x.x.x:37291: listen udp4 0.0.0.0:0: socket: too many open files
```

**Comment by backkem** [comment]
The most likely problem seems to be that the `RelaySockets` are leaking. This won't be easy to debug without the ability to reproduce. Maybe the logs could contain a clue. If not, are you able to dig into the code to assist in debugging?

One thing I did notice is that a `Refresh` requests with a 0 duration seem to cause the `lifetimeTimer` to be stopped. That could cause the associated `RelaySocket` to never be closed. This is just a wild guess at this point thought.

**Comment by Sean-Der** [comment]
Sorry this took so long @superp00t I am taking a break from working on `pion/webrtc` and want to spend some time on TURN.
