### ISSUE TITLE
Simplify NewServer()

### ISSUE THREAD

**Issue by stv0g** [pion/turn#286]
The cognitive complexity of `NewServer()` is too high (36 > 30).

@rg0now has proposed the following change in #267 which I support:

> I tend to agree with this: `NewServer` was already rather complex in the first place. We've added
> just 6 new lines of new fairly trivial code to handle the permissionHandlers.
> 
> One way to go about this is to separate out the two loop bodies into a separate function each. Namely, the code that sets up PacketConnConfigs and calls the readLoop from https://github.com/pion/turn/blob/371fc35851d91a885a0621b295f8e9a3ed6af2d2/server.go#L68 to https://github.com/pion/turn/blob/371fc35851d91a885a0621b295f8e9a3ed6af2d2/server.go#L85 could go into a new function, say, `runPacketConn`, and the code that sets up the ListenerConfigs from https://github.com/pion/turn/blob/371fc35851d91a885a0621b295f8e9a3ed6af2d2/server.go#L90 to https://github.com/pion/turn/blob/371fc35851d91a885a0621b295f8e9a3ed6af2d2/server.go#L114 could be refactored into a function called `runListener` or similar. Would you be willing to take such a patch?

**Comment by pristupaanastasia** [comment]
Hi, can I take this task?

**Comment by stv0g** [comment]
> Hi, can I take this task?

Sure, a PR would be very welcome :) Maybe just align with @rg0now and his changes in #288.

**Comment by rg0now** [comment]
Hi @pristupaanastasia, thanks for https://github.com/l7mp/turn/pull/1. I think your change is OK. However, I'm not sure it's optimal to base your PR on #288: there is a lot to do on #288 until it gets in a mergeable form and it would be shame to delay your change until that happens. My suggestion would be to rebase your PR on top of pion/turn master and submit it here as an independent patch, and once it's merged I'll rebase @288 on top of your change. Wdyt?

**Comment by stv0g** [comment]
Done 🥳
