### ISSUE TITLE
Use netip.AddrPort for FiveTuple to reduce lookup times

### ISSUE THREAD

**Issue by stv0g** [pion/turn#299]
Thanks to @rg0now new benchmarks (see #298) we have some number about the cost of the current allocation lookup:

> One minor outlier is UDPAddr.String(): we spend almost 7% of the total running time stringifying UDP addresses. The major user is the allocation manager's GetAllocation() routine (>4% total running time) that calls Fivetuple.FingerPrint() per each received packet to find the allocation in the allocation map, effectively calling UDPAddr.Stringify() per each packet multiple times (see attached screenshot). I'm wondering whether we could (and should) try to optimize this.

I think we should modernize the code and use the netip package here. We could use its AddrPort type to make the FiveTuple comparable and hence get rid of the stringification completely :)

> As per `netip.AddrPort`: I guess the definition of FiveTuple would change as follows:
> 
> ```go
> type FiveTuple struct {
> 	Protocol
> 	SrcAddr, DstAddr netip.AddrPort
> }
> ```

Yes exactly.

> Now I see that `netip.AddrPort` is safe for comparison, but is the struct it is embedded in also comparable?

Yes. The [language spec says](https://go.dev/ref/spec#Comparison_operators):

> Struct types are comparable if all their field types are comparable. Two struct values are equal if their corresponding non-[blank](https://go.dev/ref/spec#Blank_identifier) field values are equal. The fields are compared in source order, and comparison stops as soon as two field values differ (or all fields have been compared).

> I mean, with the new definition can we write this?
> 
> ```go
> // Equal asserts if two FiveTuples are equal
> func (f *FiveTuple) Equal(b *FiveTuple) bool {
> 	return *f == *b
> }
> ```

Yes we can. But I think an `Equal()` function is not even required here.

> And then, can we also use the FiveTuple directly as a map key?

Yes, as all the fields of `FiveTuple` are comparable themself.

```go
// Manager is used to hold active allocations
type Manager struct {
...
	allocations  map[FiveTuple]*Allocation
...
}
```

```go
// GetAllocation fetches the allocation matching the passed FiveTuple
func (m *Manager) GetAllocation(fiveTuple *FiveTuple) *Allocation {
	return m.allocations[*fiveTuple]
}
```

> My understanding is that this all would be OK, but I've never used netip nor struct-as-map-key myself.

Yes :)

> And if this is all OK, are you willing to take a PR that makes this change? Is it OK to add a new package dependency?

Yes. I created this new issue to track the PR.

**Comment by stv0g** [comment]
> Is it OK to add a new package dependency?

`netip` is actually part of the Go standard library (since 1.18).

Hence, we might need to increase the Go version in `go.mod`

**Comment by rg0now** [comment]
I'll be happy to do this if no one else jumps in, feel free to assign this issue to me.

**Comment by stv0g** [comment]
Yes definitely :) Your contributions are very welcome!

**Comment by stv0g** [comment]
Postponed until we switch t o Go > 1.18 Pion-wide
