### ISSUE TITLE
Finish logging design

### ISSUE THREAD

**Issue by Sean-Der** [pion/turn#3]
Since we are embedded we should probably allow people to bring their own logger (and default to zerolog to the examples?)

**Comment by enobufs** [comment]
All pion modules are now using pion/logging while the logging module still allows users to integrate other loggers with it.

The PR #52 also introduces pion/logger support (finally)!

**Comment by Sean-Der** [comment]
@enobufs nice work, just going through and triaging stuff great to see this :D

**Comment by enobufs** [comment]
Now it has logger!
