### ISSUE TITLE
Using TURN server with two public IPs

### ISSUE THREAD

**Issue by kbats183** [pion/turn#313]
Hello! Thank you for your platform.

I have a strange way of using webrtc in my project. I have two isoalted networks with server between they (let's call this network A and B).  I would like to use pion turn server to view webrtc streams on network B from computers on network A.

I have seen examples, but I do not know which public ip I should use as a parameter?

**Comment by Justme0** [comment]
TURN could provide only one public address for two network A and B. TURN will allocate two different `Allocation` data structure for A and B. Five-tuple(client's IP address, client's port, server IP address, server port, and transport protocol) identifies an allocation.

**Comment by stv0g** [comment]
I think you might be able to work around this with running two instances of TURN server. One for each network. In this case, you would use the public IP of the server in the associated isolated network.
