### ISSUE TITLE
How to use log tracking in turn server?

### ISSUE THREAD

**Issue by gsmini** [pion/turn#319]
in my project , i need to print the deviceid when turn server given a relay address to deivce, and also when a device lost conntions with turn server so that i can debug device status in ELK.
but i didn’t  find a hook function , struct or lifecycle function in turn server source code to solve this problem. so i help me ,thanks!

that is all i need:

- when turn server allocate a relay address, i need print "deviceid jnsdau73hasd get relay addr success: 127.0.0.1:38811 "
- when the allocation manager delete a  allocation, i need print  "delete deviceid jnsdau73hasd relay addr success: 127.0.0.1:38811 "

**Comment by rg0now** [comment]
AFAIK there is indeed no hook in pion/turn for event reporting. 

Question is, whether you want a quick and dirty solution, or you want to get your feet wet and do some coding:
- the ugliest solution would to parse the pion/turn logs, but in general I'd not recommend this unless you need something badly that works right now (and I'm not sure we get a log every time an allocation is closed))
- the allocation manager calls the user-supplied `PacketConnConfig.AllocatePacketConn` when making a new connection so you can report new allocations from this function (but at this point it is not 100% that the allocation will be successful), and you can return an overloaded `net.PacketConn` that will report the deletion of the allocation when the underlying `RelayConn` is closed (assuming that your relay connections will be properly closed, which is not always the case); see an example [here](https://pkg.go.dev/github.com/abdulhaseeb08/livekit-server/pkg/telemetry)
- the best solution would be to create general event-reporting framework in pion/turn (and maybe in the entire pion/webrtc framework): I'd prefer OpenTelemetry or Prometheus events, both allow you to trace what's going on from a central telemetry service (see again the above example)

**Comment by stv0g** [comment]
Thanks @rg0now for answering the question with so much detail :)

@gsmini I will close the issue as your question seems to be answered.

For general support, I also recommend that you join the Pion community Slack channel which is linked in the repo's README.
