### ISSUE TITLE
github.com/pion/ice/v2@v2.3.8/gather.go:657:21: cannot use turnServerAddr (variable of type string) as net.Addr value in struct literal: string does not implement net.Addr (missing method Network)

### ISSUE THREAD

**Issue by yangyile1990** [pion/turn#339]
github.com/pion/ice/v2@v2.3.8/gather.go:657:21: cannot use turnServerAddr (variable of type string) as net.Addr value in struct literal: string does not implement net.Addr (missing method Network)

**Comment by Sean-Der** [comment]
@stv0g Would you mind partially reverting 79fbb4e3

It looks like the public API was changed https://github.com/pion/turn/commit/79fbb4e3#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfR35 

With the new v2.1.1 tag all dependents are going to break. If you don't have the time to do it today I should be able to get it after family goes to bed.

thanks!

**Comment by Sean-Der** [comment]
Hi @yangyile1990 would you mind trying again? This should be fixed now!

**Comment by yangyile1990** [comment]
OK, the problem is fixed, thank you.
