### ISSUE TITLE
 no such user exists

### ISSUE THREAD

**Issue by Raksha-CPU** [pion/turn#349]
Hello Team,

I'm currently setting up a Pion TURN server on an Amazon Linux machine running Ubuntu 20.04 LTS. Here's what I've done so far:

I cloned the Pion TURN server repository and navigated to the appropriate directory. i.e, turn/examples/turn-server/tcp
I built the server using the command "go build".
go build -o pion_turnserver main.go
Then, I launched the server using the command "sudo ./pion_turnserver" with the IP address, port, user credentials, and realm.
sudo ./pion_turnserver -public-ip "x.x.x.x" -port "443" -users "username=password,raksha=raksha123" -realm "mydomain.com"
I have also tried with different combination for users flag

Now, I'm integrating this TURN server with a Jitsi application by configuring environment variables as follows:

For "TURN_CREDENTIALS," I set the value to "username=password,raksha=raksha123"
I defined "TURN_HOST" as "mydomain.com"
The "TURN_PORT" is set to "443."
"TURNS_HOST" is set to "mydomain.com"
Lastly, "TURNS_PORT" is set to "443."
However, when I attempt to make a call using the Jitsi app, the Pion TURN server logs display the following errors:

Failed to handle datagram: Failed to handle Allocate-request from 10.60.128.6:52570: No such user exists (Error code: 1692785230)
Failed to handle datagram: Failed to handle Allocate-request from 10.60.128.7:20826: No such user exists (Error code: 1692785243)
Failed to handle datagram: Failed to handle Allocate-request from 10.60.128.6:25761: No such user exists (Error code: 1692785230)

Could you please suggest here?

Update: I noticed that If I don't give realm flag, I don't get "no such user exists" error.. Can you please tell me how to make it work with my own domain?

**Comment by silently** [comment]
I don't know about JITSI, but this option:
`-users "username=password,raksha=raksha123"`
is a comma-separated list of username=credential, so I guess you should give one username and one credential to JITSI, and not the full string "username=password,raksha=raksha123"

**Comment by rg0now** [comment]
Closing this as inconclusive. Feel free to reopen if something important comes up.
