### ISSUE TITLE
Off-the-shelf solution

### ISSUE THREAD

**Issue by backkem** [pion/turn#37]
We currently provide a binary release where you can configure the port & users with environment variables. This is rather limited. We should look into supporting multiple ways of configuration and authentication. E.g.: multiple off-the-shelf version of `AuthenticateRequest`. It's not entirely clear yet how to best do this. It's probably infeasible to support any kind of configuration and authentication source imaginable. Maybe there is a good balance.

One thing to consider is that this will probably introduce additional external dependencies. This should definitely be avoided in this repo since it will likely become a dependency of `pions/webrtc` at some point. Therefore, one thing to consider is creating a `pions/turn-server` repo where we build out the more fully featured off-the-shelf server.

## Alternatives

- Document that this is not our focus and more clearly show how to build your own solution.

## Additional context

This point has come up a couple times now:
- #21 
- #36 (cc @PertsevRoman)

**Comment by Sean-Der** [comment]
I updated the documentation to reflect we are building an API, and not a server!

If anyone in the future wants to contribute more featureful examples I would love to have them. For the time being I am personally happy with how the repo looks. I am using `pion/turn` in production and have been modifying/designing it for my needs. I would love to get others feedback though!

thanks
