### ISSUE TITLE
Payload modification

### ISSUE THREAD

**Issue by josefhernandez** [pion/turn#388]
## Summary

Intercept and modify audio package

## Motivation

We receive audio from client and need to intercept, modify, apply an audio filter, and forward it to the other end

## Describe alternatives you've considered

Log example includes the following doc:
```
// stunLogger wraps a PacketConn and prints incoming/outgoing STUN packets
// This pattern could be used to capture/inspect/modify data as well
```

**Comment by Sean-Der** [comment]
Hey @josefhernandez 

You will need to use WebRTC Server/SFU for this, or do it client side.

With TURN the connection is E2E encrypted so you will not be able to modify data as it is flowing through the TURN server.

If you have further questions I am available in [Slack](https://pion.ly/slack) to help!
