### ISSUE TITLE
Help Wanted: Example for tls turn client ( pion webrtc )

### ISSUE THREAD

**Issue by RohanDoshi21** [pion/turn#396]
The example mentioned in turn-server/tls let's me configure TLS enabled turn server.

I am using pion/webrtc, where I am providing it to the ICEServer, how can I enable TLS here ?

**Comment by rg0now** [comment]
Here's a snippet of code to use a TURN server over TLS in pion/webrtc:

```
// Set the ICE server config
config := webrtc.Configuration{
	ICEServers: []webrtc.ICEServer{
		{
			URLs: []string{"turns:<TURN_SERVER_IP_ADDRESS>:<TURN_SERVER_PORT>?transport=tcp"},
			Username: "<USERNAME>",
			Credential: "<PASSWORD>",
		},
	},
}

// Create a new RTCPeerConnection
peerConnection, err := api.NewPeerConnection(config)
```

For the specification of the TURN URI format see the RFC [here](https://datatracker.ietf.org/doc/html/rfc7065#section-3). Plus there are millions of examples on how to use pion/webrtc [here](https://github.com/pion/webrtc/tree/master/examples).
