### ISSUE TITLE
When will DTLS be supported

### ISSUE THREAD

**Issue by hudson-s** [pion/turn#416]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome? Is this available in other implementations? Can this not be implemented using primitives?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered.

**Comment by rg0now** [comment]
DTLS *is* supported. What is your question?

**Comment by hudson-s** [comment]
Thank you. I didn't see any mention of support

**Comment by hudson-s** [comment]
> DTLS _is_ supported. What is your question?

Thank you. I didn't see any mention of support
