### ISSUE TITLE
How to get peer's transport address

### ISSUE THREAD

**Issue by henryZhangDev** [pion/turn#42]
assume that We have 4 entities:
a). TURN Server (T): listening on public IP
b). TURN Client (C): somebody behind NAT that wants to connect other peer
c). Peer (P): somebody behind NAT that wants to talk with C
d). Signaling Server(S): intermediate server which helps connection setup between C and P

The process is like follows:

1)  C goes to T and asks for IP:PORT
2). T allocates IP:PORT. It is called RELAYED ADDRESS. All data received on that address will be sent back to C. Also, C can use TURN to send data from that address to allowed peers.
3). Now, C sends to P its RELAYED ADDRESS via S
4). P get its transport address between P and RELAYED ADDRESS 
5). P send its transport address to C via S
6). C create permission of P's transport address

The issue happens in #4 in case of Symmetric  NAT that P should send BindRequest to RELAYED ADDRESS, but rfc5766 and pion/turn's implementation explicitly says that only UDP datagram allowed between T and P, how does it work?

Thanks in advance

**Comment by enobufs** [comment]
@henryZhangDev I could not understand your question or issue above well... By (4), P learns C's relayed address, so P can start sending a connectivity check packets (Binding Request) to the relayed address, which would be done automatically by ICE (pion/ice) for you.

**Comment by Sean-Der** [comment]
Hey @henryZhangDev 

If you have more questions I am happy to help! I don't have anything to add over @enobufs question. It might be helpful to run two `pion/ice` agents against `pion/turn` then you can see everything interact.

If I can be helpful I am happy to talk in [Slack](https://pion.ly/slack) anytime!
