### ISSUE TITLE
 BadFormat for message/cookie: 74686368 is invalid magic cookie (should be 2112a442)

### ISSUE THREAD

**Issue by hudson-s** [pion/turn#425]
09:34:10.096773 server.go:229: turn ERROR: Failed to handle datagram: failed to create stun message from packet: BadFormat for message/cookie: 74686368 is invalid magic cookie (should be 2112a442)

**Comment by rg0now** [comment]
What is your question?

**Comment by hudson-s** [comment]
Yes, there is no head. We want to reduce the amount of data transfer, will it affect

**Comment by rg0now** [comment]
Well, the TURN server needs a valid TURN packet to work with, and that will need the TURN protocol header...

**Comment by hudson-s** [comment]
What is the meaning of this log? Do I need to care about it:

`No Permission or Channel exists for 10.0.0.66:47104 on allocation 10.0.0.66:58632 (suppressed 175 log events)
`

**Comment by hudson-s** [comment]
> Well, the TURN server needs a valid TURN packet to work with, and that will need the TURN protocol header...

In fact, I did not find this problem when using cotrun tests before. I would like to ask if this is in the rfc protocol? I want to study

**Comment by hudson-s** [comment]
By the way, although this is wrong, I can still see the real-time picture on my live stream. (I don't use a streaming server)

**Comment by rg0now** [comment]
Closing this since, judging from the below, you must be working with [STUNner](https://github.com/l7mp/stunner):
```
`No Permission or Channel exists for 10.0.0.66:47104 on allocation 10.0.0.66:58632 (suppressed 175 log events)
file_client.go:214: config-file-client WARNING: Waiting for config file "etc/stunnerd/stunnerd.conf"
```

This is the issue tracker of pion/turn, the TURN implementation that underlies STUNner. Please reopen the issue there.
