### ISSUE TITLE
pls help with powershell

### ISSUE THREAD

**Issue by ninenite** [pion/turn#47]
how to install turn server with powershell (windows server2012)

thank a lot i think

**Comment by songjiayang** [comment]
you can download the Windows binary with [link](https://github.com/pion/turn/releases/download/1.0.3/simple-turn-windows-amd64.exe)  or use command `go get github.com/pion/turn/cmd/simple-turn`

**Comment by Sean-Der** [comment]
Hi @ninenite 

Sorry for the delay, but I have updated the documentation to explain how to use Go to build the examples. I also generate binaries for the examples if you want to quickly deploy the existing ones.

Thanks!
