### ISSUE TITLE
TURN server should behave 'address-restricted-filtering'

### ISSUE THREAD

**Issue by enobufs** [pion/turn#65]
### Your environment.
  - Version: v1.2.0
  - Browser: n/a

### What did you do?
I wrote a test: https://github.com/pion/ice/blob/topic-vnet/connectivity_vnet_test.go
in which there are symmetric NATs on both ends, if one end did not have TURN server URL (but has STUN server URL), the connection fails! 

### What did you expect?
srflx-relay pair should succeed, when both ends have a symmetric NAT, and only one end have TURN server URL.

### What happened?
Connection fails.
Looking at [this spec](https://tools.ietf.org/html/rfc5766#section-2.3), TURN server (Permission) should do `address-restricted filtering`
```
To ease concerns amongst enterprise IT administrators that TURN could be used to bypass corporate firewall security, TURN includes the notion of permissions. TURN permissions mimic the address-restricted filtering mechanism of NATs that comply with [RFC4787].
```

But looking at the current implementation of TURN permission, the fingerprint includes port number...  We should exclude the port number from the fingerprint and its comparison with the srcAddr.

@songjiayang Can you confirm my above observation?

**Comment by enobufs** [comment]
Looking at coturn, its permission hashtable only evaluate IP address/family, not port: https://github.com/coturn/coturn/blob/master/src/server/ns_turn_allocation.c#L248

We should do the same!

**Comment by songjiayang** [comment]
@enobufs You are right. With RFC 5766, `Permission`  only include IP and `ChannelBind` with IP and port.  I have created  the same issue https://github.com/pion/turn/issues/41 for this problem.
