### ISSUE TITLE
[WIP] Rename 'cmd' folder to 'examples'

### ISSUE THREAD

**Issue by enobufs** [pion/turn#66]
The pion/turn is a library, not the application, as @Sean-Der intended.  We should move simple-turn and client applications into 'examples' folder.

Also, I believe we should consider removing client API (and cmd/client also), and use pion/turnc instead.

**Comment by Sean-Der** [comment]
👍

We should probably also write about this more/explain the design decision. I will open a PR for that!

**Comment by enobufs** [comment]
@Sean-Der 
I think we should remove the docker files as well (to reduce our maintenance cost).. ok with you?

**Comment by Sean-Der** [comment]
Yea @enobufs that is a great idea.

I will drop a PR for this soon! I will write a nice explanation that we are doing `TURN as an API` for Server and Client.

Also I am thinking we should direct people to coturnd and gortc if they are looking for a TURN server and not the flexibility.

**Comment by enobufs** [comment]
Great!
@Sean-Der I had to write another command-line tool as an example to test with coturn.
(I have fixed all problems with coturn!)

Please let me push a PR that moves cmd to examples because I created the above tool in the examples folder already...

**Comment by enobufs** [comment]
It is `cmd2examples` branch.
