### ISSUE TITLE
How to make Pion TURN work with SSL?

### ISSUE THREAD

**Issue by ghost** [pion/turn#81]
Hello, thanks for the nice alternative.
Can Pion TURN work with SSL?

**Comment by daenney** [comment]
I would expect that can be done with github.com/pion/dtls. You'll have to `dtls.Dial()` first which returns a `dtls.Conn`, which implements the `net.PacketConn` interface. B/c of this you can set the returned conn from a `dtls.Dial()` on `turn.ClientConfig.Conn`. You can do the same thing for the server side by using `dlts.Listen()` instead.

I'm not sure if this works, but I would expect it does.

**Comment by daenney** [comment]
On second thought, I might be wrong. `dtls.Dial()` gives us a `net.Conn`, not a `net.PacketConn` and `dtls.Listen` gives us a `net.Listener`.

**Comment by daenney** [comment]
@Sean-Der You're a lot more well versed in this than I am. If I look at the code, I don't think we can just wrap pion/dtls around it and have it work, so providing easy options for it would be hard to.

What do we need to do to make it happen? And does it make sense?

**Comment by Sean-Der** [comment]
This is done!

The Server now accepts a slice of `PacketConnConfig` or `ListenerConfig`. With `ListenerConfig` you can pass anything that implements the `net.Listener` interface.

so `pion/turn` can now use the result from `tls.Listen` or it can use the `Listener` that is provide by `pion/dtls`!

**Comment by acondura** [comment]
Could you please show an example how we could use SSL certs with this for example https://github.com/pion/turn/tree/master/examples/turn-server/tcp?

**Comment by dhaminitinAltran** [comment]
Hi has anyone used this with SSL where or how do we need to provide the certificates for configuring?
