### ISSUE TITLE
Management interface

### ISSUE THREAD

**Issue by Sean-Der** [pion/turn#9]
Do we provide an HTTP endpoint so people can see the status of allocations?

**Comment by backkem** [comment]
Maybe you could do a metrics middleware instead? E.g. one exposing a [Prometheus ](https://github.com/prometheus/client_golang) endpoint. That would also allow managing distributed setups.

**Comment by Sean-Der** [comment]
Closing this for now.

The idea of `pion/turn` is to provide TURN as an API. So I personally don't want to ship anything pre-built at this time.

However! If people want more APIs/information would love to hear :)
