### ISSUE TITLE
Can the REALM just be the public DNS of the EC2 instance?

### ISSUE THREAD

**Issue by AlekRuzic** [pion/turn#95]
I created a fresh linux ec2 instance and ran all the commands. My turn server still doesn't seem to be working. Is it fine that I used my public DNS? I can't think of any other way to do it. 

Are there any steps I may be missing? I literally just created the instance and ran the 6 commands.

**Comment by Sean-Der** [comment]
Hi @AlekRuzic 

Sorry for the relay, I just released `v2` with updated commands. If you get a chance would love if you could try it out again!
